#Dockerfile-2
FROM ubuntu:14.04
LABEL name="vishwajit"
LABEL email="vishwajitadcet@gmail.com"
ENV NAME vishwajit
ENV PASS password123
RUN pwd > /tmp/1stpwd.txt
RUN cd /tmp
WORKDIR /tmp
RUN cat 1stpwd.txt
